
server:
  port: 8843

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: spring-resource-server
    output.ansi.enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:8891